# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  driverPathAndName: $(System.DefaultWorkingDirectory)/chromedriver
  driverType: 'CHROME_HEADLESS'
  pageTimeout: 60

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      chromeVersion=$(google-chrome --product-version | grep -iE "[0-9.]{10,20}")
      wget "https://chromedriver.storage.googleapis.com/${chromeVersion}/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip
      chmod +x chromedriver

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    options: '-q -DdriverType=$(driverType) -DpageTimeout=$(pageTimeout) -DdriverPathAndName=$(driverPathAndName)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    mavenVersionOption: 'Default'
